# Generated by Django 5.2.5 on 2025-09-03 20:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "Kickline",
            "0002_bannerpicture_button_link_bannerpicture_button_text_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
