# Generated by Django 5.2.5 on 2025-09-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Kickline", "0003_remove_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(default="N/A", max_length=100),
        ),
    ]
