# Generated by Django 5.2.5 on 2025-09-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Kickline", "0004_product_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Section"),
                            ("categories", "Premium Categories"),
                            ("featured", "Featured Products"),
                            ("about", "About Section"),
                            ("contact", "Contact Section"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("image", models.ImageField(upload_to="backgrounds/")),
                (
                    "overlay_opacity",
                    models.FloatField(
                        default=0.8, help_text="Overlay opacity (0.0 to 1.0)"
                    ),
                ),
                (
                    "overlay_color",
                    models.CharField(
                        default="#0E1C36",
                        help_text="Overlay color (hex code)",
                        max_length=7,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Background Image",
                "verbose_name_plural": "Background Images",
                "ordering": ["section"],
            },
        ),
    ]
