# Generated by Django 5.2.5 on 2025-09-08 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Kickline", "0006_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="replied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ContactReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reply_subject", models.CharField(max_length=200)),
                ("reply_message", models.TextField()),
                ("sent_by", models.CharField(default="Kickline Team", max_length=100)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("email_sent", models.BooleanField(default=False)),
                (
                    "contact_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="Kickline.contactmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Reply",
                "verbose_name_plural": "Contact Replies",
                "ordering": ["-sent_at"],
            },
        ),
    ]
